### ISSUE TITLE
Small CPU utilization during training

### ISSUE THREAD

**Issue by Ishitori** [awslabs/graphstorm#528]
Hi team,

I use graphstorm to do Link Prediction on a single machine. I construct my graph `gconstruct` as `DistDGL`, because it looks like that `gsgnn_lp.py` can only accept Distributed DGL as an input (one of the input arguments is `--part-config`).

I use  `gsgnn_lp.py` to train the model with pretty much default arguments. My train config is below:

```
version: 1.0
gsf:
    basic:
        model_encoder_type: rgcn
        backend: gloo
        verbose: false
    gnn:
        fanout: "50,50"
        num_layers: 2
        hidden_size: 32
        use_mini_batch_infer: false
    input:
        restore_model_path: null
    output:
        save_model_path: {save_models_path}
        save_embeds_path: {save_embeds_path}
    hyperparam:
        dropout: 0.1
        lr: 0.0005
        num_epochs: 5
        batch_size: 1024
        wd_l2norm: 0.1
        alpha_l2norm: 0.00001
        gnn_norm: "layer"
        num-ffn-layers-in-input: 1
        num_ffn_layers_in_gnn: 1
    rgcn:
        num_bases: -1
        use_self_loop: true
        sparse_optimizer_lr: 1e-2
        use_node_embeddings: false
    link_prediction:
        num_negative_edges: 32
        num_negative_edges_eval: 10000
        lp_decoder_type: DistMult
        lp_loss_func: cross_entropy
        train_negative_sampler: joint
        lp_edge_weight_for_loss:
        - "weight"
        eval_etype:
        - "{etype_1}"
        - "{etype_2}"
        train_etype:
        - "{etype_1}"
        - "{etype_2}"
        exclude_training_targets: false
        reverse_edge_types_map: []
```

I have a 32 core machine.

What I am surprised is that only 2 cores of my machine are used. The rest are not used at all, and because of that training is super slow... I am puzzled why it doesn't use all the cores as a I assume there is a lot of heavy lifting done by CPUs...

Is it due to distributed nature of GraphStorm? If so, is there a particular configuration I can set, to instruct graph storm that we are in a non-distributed environment to speed things up? Any other reasons, like misconfiguration or something?

Thank you.
